export const genreMapping = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  18: "Drama",
  10751: "Family",
  14: "Fantasy",
  36: "History",
  27: "Horror",
  10402: "Music",
  9648: "Mystery",
  10749: "Romance",
  878: "Science Fiction",
  10770: "TV Movie",
  53: "Thriller",
  10752: "War",
  37: "Western",
};

export const seats = [
  {
    id: "A1",
    row: "A",
    seatNumber: 1,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A2",
    row: "A",
    seatNumber: 2,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A3",
    row: "A",
    seatNumber: 3,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A4",
    row: "A",
    seatNumber: 4,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A5",
    row: "A",
    seatNumber: 5,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A6",
    row: "A",
    seatNumber: 6,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A7",
    row: "A",
    seatNumber: 7,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A8",
    row: "A",
    seatNumber: 8,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A9",
    row: "A",
    seatNumber: 9,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A10",
    row: "A",
    seatNumber: 10,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A11",
    row: "A",
    seatNumber: 11,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A12",
    row: "A",
    seatNumber: 12,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A13",
    row: "A",
    seatNumber: 13,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A14",
    row: "A",
    seatNumber: 14,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "A15",
    row: "A",
    seatNumber: 15,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },

  {
    id: "B1",
    row: "B",
    seatNumber: 1,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B2",
    row: "B",
    seatNumber: 2,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B3",
    row: "B",
    seatNumber: 3,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B4",
    row: "B",
    seatNumber: 4,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B5",
    row: "B",
    seatNumber: 5,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B6",
    row: "B",
    seatNumber: 6,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B7",
    row: "B",
    seatNumber: 7,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B8",
    row: "B",
    seatNumber: 8,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B9",
    row: "B",
    seatNumber: 9,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B10",
    row: "B",
    seatNumber: 10,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B11",
    row: "B",
    seatNumber: 11,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B12",
    row: "B",
    seatNumber: 12,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B13",
    row: "B",
    seatNumber: 13,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B14",
    row: "B",
    seatNumber: 14,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "B15",
    row: "B",
    seatNumber: 15,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },

  {
    id: "C1",
    row: "C",
    seatNumber: 1,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C2",
    row: "C",
    seatNumber: 2,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C3",
    row: "C",
    seatNumber: 3,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C4",
    row: "C",
    seatNumber: 4,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C5",
    row: "C",
    seatNumber: 5,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C6",
    row: "C",
    seatNumber: 6,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C7",
    row: "C",
    seatNumber: 7,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C8",
    row: "C",
    seatNumber: 8,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C9",
    row: "C",
    seatNumber: 9,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C10",
    row: "C",
    seatNumber: 10,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C11",
    row: "C",
    seatNumber: 11,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C12",
    row: "C",
    seatNumber: 12,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C13",
    row: "C",
    seatNumber: 13,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C14",
    row: "C",
    seatNumber: 14,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },
  {
    id: "C15",
    row: "C",
    seatNumber: 15,
    category: "Premium",
    rate: 200,
    isBooked: false,
  },

  {
    id: "D1",
    row: "D",
    seatNumber: 1,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D2",
    row: "D",
    seatNumber: 2,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D3",
    row: "D",
    seatNumber: 3,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D4",
    row: "D",
    seatNumber: 4,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D5",
    row: "D",
    seatNumber: 5,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D6",
    row: "D",
    seatNumber: 6,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D7",
    row: "D",
    seatNumber: 7,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D8",
    row: "D",
    seatNumber: 8,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D9",
    row: "D",
    seatNumber: 9,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D10",
    row: "D",
    seatNumber: 10,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D11",
    row: "D",
    seatNumber: 11,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D12",
    row: "D",
    seatNumber: 12,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D13",
    row: "D",
    seatNumber: 13,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D14",
    row: "D",
    seatNumber: 14,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "D15",
    row: "D",
    seatNumber: 15,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },

  {
    id: "E1",
    row: "E",
    seatNumber: 1,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E2",
    row: "E",
    seatNumber: 2,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E3",
    row: "E",
    seatNumber: 3,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E4",
    row: "E",
    seatNumber: 4,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E5",
    row: "E",
    seatNumber: 5,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E6",
    row: "E",
    seatNumber: 6,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E7",
    row: "E",
    seatNumber: 7,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E8",
    row: "E",
    seatNumber: 8,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E9",
    row: "E",
    seatNumber: 9,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E10",
    row: "E",
    seatNumber: 10,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E11",
    row: "E",
    seatNumber: 11,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E12",
    row: "E",
    seatNumber: 12,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E13",
    row: "E",
    seatNumber: 13,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E14",
    row: "E",
    seatNumber: 14,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "E15",
    row: "E",
    seatNumber: 15,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },

  {
    id: "F1",
    row: "F",
    seatNumber: 1,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F2",
    row: "F",
    seatNumber: 2,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F3",
    row: "F",
    seatNumber: 3,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F4",
    row: "F",
    seatNumber: 4,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F5",
    row: "F",
    seatNumber: 5,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F6",
    row: "F",
    seatNumber: 6,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F7",
    row: "F",
    seatNumber: 7,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F8",
    row: "F",
    seatNumber: 8,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F9",
    row: "F",
    seatNumber: 9,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F10",
    row: "F",
    seatNumber: 10,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F11",
    row: "F",
    seatNumber: 11,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F12",
    row: "F",
    seatNumber: 12,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F13",
    row: "F",
    seatNumber: 13,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F14",
    row: "F",
    seatNumber: 14,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },
  {
    id: "F15",
    row: "F",
    seatNumber: 15,
    category: "Executive",
    rate: 150,
    isBooked: false,
  },

  {
    id: "G1",
    row: "G",
    seatNumber: 1,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G2",
    row: "G",
    seatNumber: 2,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G3",
    row: "G",
    seatNumber: 3,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G4",
    row: "G",
    seatNumber: 4,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G5",
    row: "G",
    seatNumber: 5,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G6",
    row: "G",
    seatNumber: 6,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G7",
    row: "G",
    seatNumber: 7,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G8",
    row: "G",
    seatNumber: 8,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G9",
    row: "G",
    seatNumber: 9,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G10",
    row: "G",
    seatNumber: 10,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G11",
    row: "G",
    seatNumber: 11,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G12",
    row: "G",
    seatNumber: 12,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G13",
    row: "G",
    seatNumber: 13,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G14",
    row: "G",
    seatNumber: 14,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "G15",
    row: "G",
    seatNumber: 15,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },

  {
    id: "H1",
    row: "H",
    seatNumber: 1,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H2",
    row: "H",
    seatNumber: 2,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H3",
    row: "H",
    seatNumber: 3,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H4",
    row: "H",
    seatNumber: 4,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H5",
    row: "H",
    seatNumber: 5,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H6",
    row: "H",
    seatNumber: 6,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H7",
    row: "H",
    seatNumber: 7,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H8",
    row: "H",
    seatNumber: 8,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H9",
    row: "H",
    seatNumber: 9,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H10",
    row: "H",
    seatNumber: 10,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H11",
    row: "H",
    seatNumber: 11,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H12",
    row: "H",
    seatNumber: 12,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H13",
    row: "H",
    seatNumber: 13,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H14",
    row: "H",
    seatNumber: 14,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "H15",
    row: "H",
    seatNumber: 15,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },

  {
    id: "I1",
    row: "I",
    seatNumber: 1,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I2",
    row: "I",
    seatNumber: 2,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I3",
    row: "I",
    seatNumber: 3,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I4",
    row: "I",
    seatNumber: 4,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I5",
    row: "I",
    seatNumber: 5,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I6",
    row: "I",
    seatNumber: 6,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I7",
    row: "I",
    seatNumber: 7,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I8",
    row: "I",
    seatNumber: 8,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I9",
    row: "I",
    seatNumber: 9,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I10",
    row: "I",
    seatNumber: 10,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I11",
    row: "I",
    seatNumber: 11,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I12",
    row: "I",
    seatNumber: 12,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I13",
    row: "I",
    seatNumber: 13,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I14",
    row: "I",
    seatNumber: 14,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
  {
    id: "I15",
    row: "I",
    seatNumber: 15,
    category: "Normal",
    rate: 100,
    isBooked: false,
  },
];

export const getData = () => {
  return fetch("https://clumsy-miniskirt-tuna.cyclic.app/").then((res) =>
    res.json()
  );
};
